name = "stock"
main = "src/worker.js"
compatibility_date = "2025-12-01"

[triggers]
crons = ["10 23 * * 1-5"]

[[d1_databases]]
binding = "DB"
database_name = "stock-analysis-db"
database_id = "beab1427-4c0a-4363-9369-720c9b63e616"
